name: Hello world test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  # An arbitrary job called 'build'
  build:
    name: Hello world job
    # for our self-hosted runner, use one of the labels we defined in that runner
    runs-on: self-hosted-m1mac-hetzner
    steps:
      # Cheks ou your repository under $GITHUB_WORKSPASE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command in the runner shell
      - name: Run a one-line script
        run: echo Hello, world!  
